spring:
  jpa:
    show-sql: true
    hibernate:
      dialect: org.hibernate.dialect.SQLServer2012Dialect
      ddl-auto: update

server:
  port: 8080

azure:
  keyvault:
    client-id: 34801cb7-0b09-47d8-835a-64ae6da24eb8
    client-key: lhW7Q~G6ZxpvEysEsbtfi53IqFUUl9ipE5xoB
    enabled: true
    tenant-id: 0c11371c-423e-4cb8-9055-da976bf9304f
    uri: https://vm-school-key-vault.vault.azure.net/